/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Executive = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'name' : IDL.Text,
});
export const ProfitRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'customerTotalReceived' : IDL.Float64,
  'dailyTarget' : IDL.Float64,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'executiveName' : IDL.Text,
  'addedBy' : IDL.Text,
  'amountReceived' : IDL.Float64,
  'customerDailyTarget' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExecutive' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'changeExecutivePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteExecutive' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteRecord' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExecutive' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(Executive)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllRecords' : IDL.Func([IDL.Text], [IDL.Vec(ProfitRecord)], ['query']),
  'listExecutives' : IDL.Func([IDL.Text], [IDL.Vec(Executive)], ['query']),
  'listRecordsByExecutive' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'listRecordsByMonth' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(ProfitRecord)],
      ['query'],
    ),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'token' : IDL.Text, 'role' : IDL.Text })],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [],
      [],
    ),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Executive = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'name' : IDL.Text,
  });
  const ProfitRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'customerTotalReceived' : IDL.Float64,
    'dailyTarget' : IDL.Float64,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'executiveName' : IDL.Text,
    'addedBy' : IDL.Text,
    'amountReceived' : IDL.Float64,
    'customerDailyTarget' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExecutive' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'changeExecutivePassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteExecutive' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteRecord' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExecutive' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(Executive)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllRecords' : IDL.Func([IDL.Text], [IDL.Vec(ProfitRecord)], ['query']),
    'listExecutives' : IDL.Func([IDL.Text], [IDL.Vec(Executive)], ['query']),
    'listRecordsByExecutive' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'listRecordsByMonth' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(ProfitRecord)],
        ['query'],
      ),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'token' : IDL.Text, 'role' : IDL.Text })],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [],
        [],
      ),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'username' : IDL.Text, 'role' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };