/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Executive {
  'id' : bigint,
  'username' : string,
  'password' : string,
  'name' : string,
}
export interface ProfitRecord {
  'id' : bigint,
  'customerName' : string,
  'customerTotalReceived' : number,
  'dailyTarget' : number,
  'date' : string,
  'createdAt' : bigint,
  'executiveName' : string,
  'addedBy' : string,
  'amountReceived' : number,
  'customerDailyTarget' : number,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExecutive' : ActorMethod<[string, string, string, string], bigint>,
  'addRecord' : ActorMethod<
    [string, string, string, number, number, number, number, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string, string], undefined>,
  'changeExecutivePassword' : ActorMethod<[string, string, string], undefined>,
  'deleteExecutive' : ActorMethod<[string, bigint], undefined>,
  'deleteRecord' : ActorMethod<[string, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExecutive' : ActorMethod<[string, bigint], [] | [Executive]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllRecords' : ActorMethod<[string], Array<ProfitRecord>>,
  'listExecutives' : ActorMethod<[string], Array<Executive>>,
  'listRecordsByExecutive' : ActorMethod<[string, string], Array<ProfitRecord>>,
  'listRecordsByMonth' : ActorMethod<
    [string, bigint, bigint],
    Array<ProfitRecord>
  >,
  'login' : ActorMethod<
    [string, string],
    { 'token' : string, 'role' : string, 'mustChangePassword' : boolean }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateRecord' : ActorMethod<
    [string, bigint, string, string, number, number, number, number, string],
    undefined
  >,
  'validateSession' : ActorMethod<
    [string],
    { 'username' : string, 'role' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];